version: '3.7'

services:
  cattleweb:
    build: ./cattleweb_root
    volumes:
      - static_data:/vol/cattleweb
      - ./cattleweb_root/database:./cattleweb_root/database
    environment:
      - proddev=prod
    env_file:
      - very_secret.env
  proxy:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol
    ports:
      - "80:8000"
    depends_on:
      - cattleweb

volumes:
   static_data: