version: '3.7'

services:
  web:
    build: ./cattleweb_root
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cattleweb_root/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - cattleweb=prod