version: '3.7'

services:
  web:
    build: ./cattleweb_root
    volumes:
      - static_data:/vol/web
    environment:
      - cattleweb=prod

  proxy:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "8000:8000"
    depends_on:
      - web

volumes:
   static_data: