# Generated by Django 3.1.4 on 2020-12-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('event_description', models.CharField(max_length=200)),
            ],
        ),
    ]
