# Generated by Django 3.1.4 on 2021-02-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='next_survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
    ]
