# Generated by Django 3.1.4 on 2020-12-31 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
